### ISSUE TITLE
Dataset generation scripts?

### ISSUE THREAD

**Issue by datasith** [KeithGalli/neural-nets#3]
It would be fantastic to have a look at how you generated the datasets!

**Comment by KeithGalli** [comment]
I'll see if I can track down the code on my old PC!

**Comment by datasith** [comment]
Awesome, no pressure. I was using your repo as a reference for interview prep, and thought it'd be a nice add :) I went ahead and [created some myself](https://github.com/datasith/ds-experiments-tensorflow/blob/main/datasets/linear/linear.ipynb), so it'd be great to compare notes!

**Comment by datasith** [comment]
Thank you!

p.s., If anyone runs into this, the data-generation scripts are available [here](https://github.com/KeithGalli/neural-nets/tree/master/data-generation).

**Comment by KeithGalli** [comment]
Glad you found them! To clarify the first few examples are in graph_handle_create_data.py & the final, more complex example is in create_data.py
